update the hook

diff --git a/autosign/hooks/pre-commit b/autosign/hooks/pre-commit
--- a/autosign/hooks/pre-commit
+++ b/autosign/hooks/pre-commit
@@ -1,12 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # Run refresh regardless of what changed
 packwiz refresh
 git add pack.toml index.toml
 
 # Files to monitor and sign
-FILE="pack.toml"
-FILE_SIG="unsup.sig"
 KEY="autosign/signingkey.sec"
 
 # Exit early if private key is missing
@@ -15,17 +13,24 @@ if [ ! -f "$KEY" ]; then
     exit 1
 fi
 
-# Check if FILE is staged
-if git diff --cached --name-only | grep -q "^$FILE$"; then
-    echo "Signing $FILE..."
-    # Sign and write to .sig file
-    signify -S -s "$KEY" -m "$FILE" -x "$FILE_SIG"
-    if [ $? -ne 0 ]; then
-        echo "Failed to sign $FILE" >&2
-        exit 1
+resign() {
+    local IN="$1"
+    local OUT="$2"
+    # Check if FILE is staged
+    if git diff --cached --name-only | grep -q "^$IN$"; then
+        echo "Signing $IN..."
+        # Sign and write to .sig file
+        signify -S -s "$KEY" -m "$IN" -x "$OUT"
+        if [ $? -ne 0 ]; then
+            echo "Failed to sign $IN" >&2
+            exit 1
+        fi
+        # Stage the .sig file
+        git add "$OUT"
     fi
-    # Stage the .sig file
-    git add "$FILE_SIG"
-fi
+}
+
+resign "pack.toml" "unsup.sig"
+resign "unsup.ini" "unsup.ini.sig"
 
 exit 0
